###
POST http://localhost:5000/login?email=indria@yopmail.com&password=admin

###
GET http://localhost:5000/api/purchase
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxLCJleHAiOjE3MzI0MTY3MDcsImlhdCI6MTczMjMzMDMwN30.-F4xOJKBNXWZhuycALDsOcuBFWITGmAzverOB4pMOxA


###
GET http://localhost:5000/api/purchase/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxLCJleHAiOjE3MzI0MTY3MDcsImlhdCI6MTczMjMzMDMwN30.-F4xOJKBNXWZhuycALDsOcuBFWITGmAzverOB4pMOxA

###
POST http://localhost:5000/api/purchase
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxLCJleHAiOjE3MzI0MTY3MDcsImlhdCI6MTczMjMzMDMwN30.-F4xOJKBNXWZhuycALDsOcuBFWITGmAzverOB4pMOxA


###
PUT http://localhost:5000/api/purchase/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxLCJleHAiOjE3MzI0MTY3MDcsImlhdCI6MTczMjMzMDMwN30.-F4xOJKBNXWZhuycALDsOcuBFWITGmAzverOB4pMOxA



###
DELETE  http://localhost:5000/api/purchase/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxLCJleHAiOjE3MzI0MTY3MDcsImlhdCI6MTczMjMzMDMwN30.-F4xOJKBNXWZhuycALDsOcuBFWITGmAzverOB4pMOxA


###
GET http://localhost:5000/api/production/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxLCJleHAiOjE3MzI0MTY3MDcsImlhdCI6MTczMjMzMDMwN30.-F4xOJKBNXWZhuycALDsOcuBFWITGmAzverOB4pMOxA


###
GET http://localhost:5000/api/finishing/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxLCJleHAiOjE3MzI0MTY3MDcsImlhdCI6MTczMjMzMDMwN30.-F4xOJKBNXWZhuycALDsOcuBFWITGmAzverOB4pMOxA