server:
  host: "127.0.0.1"
  port: 5000

log:
  level: "debug" # trace | debug | info | warn | error | fatal | panic

database:
  host: "localhost"
  port: 5432
  dbName: "arbrion_db"
  username: "postgres"
  password: ""
